### PR TITLE
Support Python 3.6 so this can be used in more projects

### PR DESCRIPTION
**Pull request by TheCleric**
Was hoping to use this in a project I have that uses python < 3.8.

This PR should allow that project to work.

### CODE REVIEW

**Comment by TheCleric** [comment]
@chaychoong is this something you'd consider merging?

**Comment by jonas-eschle** [comment]
Hi, what is the status of this? I would also really like to see this merged.

**Comment by TheCleric** [comment]
Unfortunately I don't know if @chaychoong is monitoring this repo of not due to the length of time this has sat and no other commits since then. I might consider forking it if they are not interested in it any longer.

**Comment by jonas-eschle** [comment]
Yes, agree. I'd gladly install from your fork then

**Comment by TheCleric** [comment]
In light of the fact that this project appears to be unmaintained, I've created a fork under `coverage-lcov` that supports older versions of python. I have updated the README and authors to continue to give full credit to @chaychoong as the originator of this project.

https://pypi.org/project/coverage-lcov/

As of now (version 0.2.1) the only difference between this project and my fork are as follows:
- Older python support
- Add test checks on PRs
- Add test checks pre-deployment

In the future I'd like to flesh out the unit tests, add optional 3.10 validation, add mypy checking, get off black, and add lint checking.

**Comment by jonas-eschle** [comment]
Hey thanks, I'll gladly switch to that

**Comment by jonas-eschle** [comment]
Hey thanks, I'll gladly switch to that

**Comment by chaychoong** [comment]
@jonas-eschle apologies for the very very late response, somehow I missed this thread, thanks @TheCleric for the fork!

**Pull request merged**
